# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea1168686c839cf074d8497bdb9e3ddff65a967c31092430d7d349557ae595d3c63452b564e0a807ba58d73a9a87fe6a698469ec19dd1662a0daa9d457920db8

test:
  secret_key_base: 28653ac0b9a85019babd538c27634f94479e5cdec8d3fea6d4cd634f7e954e9179e063e3dad4aba4c00b1bc0813dd22c70f580846ee0575936feaff476e2f0a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
